### ISSUE TITLE
Attempt to save state beyond implementation limit

### ISSUE THREAD

**Issue by sefffal** [sefffal/PairPlots.jl#2]
Large corner plots, especially those with scatter points turned on, often hit a Plots error about attempting to save state beyond implementation limit. Noticed with GR and a similar issue with PyPlot. It might be worse when plotting contours.

This sounds like a corner case for very complicated plots.

**Comment by sefffal** [comment]
Haven't seen this error in quite a while, so most likely it has been solved upstream in Plots or GR.

**Comment by serpenttom** [comment]
When the GRUtils.plot3  run in the jupyter notebook,  it shows "attempt to save state beyond implementation limit".  However, in atom + juno , it will show the figure.

**Comment by sefffal** [comment]
Hi @serpenttom this looks like an issue in the upstream package GR.
Perhaps VS Code is rendering the plot as a png and Jupyter is rendering it as an SVG?

**Comment by sefffal** [comment]
You could try turning off the scatter points and/or contours to see if that helps.
