### ISSUE TITLE
Add support for Unitful.jl

### ISSUE THREAD

**Issue by juliohm** [sefffal/PairPlots.jl#22]
The Unitful.jl package is widely used, you could add a package extension that removes the units with `ustrip` plots and adds the labels to the axis with `unit`.

**Comment by sefffal** [comment]
That would be a nice addition 👍

**Comment by sefffal** [comment]
If we added this feature, it should ideally work with both Unitful and DynamicalQuantities.

**Comment by sefffal** [comment]
No problem! If things fall behind again, please feel free to ping me.
