### ISSUE TITLE
Patch release

### ISSUE THREAD

**Issue by eliascarv** [sefffal/PairPlots.jl#23]
I'm having some problems with PairPlots.jl as the stable version only supports StatsBase.jl 0.33 and the packages I'm using require version 0.34. Would it be possible to release a patch release of the current version of master, please?

**Comment by juliohm** [comment]
@sefffal can you please release a new patch? This is blocking some updates downstream.

Have you considered moving the package to MakieOrg so that other maintainers can help with these simple requests?

**Comment by sefffal** [comment]
Ah my apologies, I must have missed the notifications. Of course, I’ll do so right away.

**Comment by juliohm** [comment]
This issue can be closed now.
