### ISSUE TITLE
Some vectors wont plot?

### ISSUE THREAD

**Issue by mgalenb** [sefffal/PairPlots.jl#3]
Great package! I have three coefficients i am trying to make a corner plot for. For some reason, nothing gets plotted for one of the coefficients. Also the range shown on the plot is incorrect for that coefficient. the other coefficients will plot fine. It seems to be related to the amplitude of the coefficient? Here is some code that recreates the bug (i have checked in jupyter and REPL).

```
using Plots, PairPlot

stda=0.00041
a=0.073 .+ stda*randn(2000)
stdb=0.0404
b=0.116 .+ stdb*randn(2000);

table1=(;a,b)
corner(table1)
```
<img width="422" alt="Screen Shot 2021-05-12 at 12 40 14 PM" src="https://user-images.githubusercontent.com/6004917/118034918-654f8380-b31f-11eb-858b-2622b726deee.png">

```
stdc=stda*100
c=0.073 .+ stdc*randn(2000);

table2=(;b,c)
corner(table2)

****THIS PLOT WORKS****
```

It seems like if the variance is too small `stda` then it doesn't get plotted. Maybe this is intentional? Is there a better way to plot small values?

**Comment by sefffal** [comment]
Thanks so much for the bug report! This seems to have been an error on my part when setting the limits on the subplots.

I've pushed a fix that appears to fix your example. You're welcome to test it out on the `main` branch, if you like (`] add PairPlots#main`).

I'll register a new version later today.

**Comment by mgalenb** [comment]
thanks for the quick fix on this! one more question. the significant figures seem to be limited to 3? so if a number is 0.004 it shows up as 0. the error estimates also work this way. is there a way to increase that to more digits or maybe switch to scientific notation?

**Comment by sefffal** [comment]
Sure no problem, I just pushed a new option `titlefmt` you could use to control that. Here's an example:
```julia
corner(table, titlefmt="\$%s = %.2f^{+%.5f}_{-%.5f}\$")
```
![image](https://user-images.githubusercontent.com/7330605/118308929-6ad4d700-b4a1-11eb-858e-17df804fb683.png)

If you need more control I could maybe swap this out for a user-provided callback that does the formatting.

Let me know if that works for you and I will tag a new release.
Thanks for the suggestions! These sort of reports will really help me add polish to the package.

**Comment by mgalenb** [comment]
that is great! thanks! this is everything I need so I think you can tag a new release if you'd like
