### ISSUE TITLE
Customization of MarginConfidenceLimits

### ISSUE THREAD

**Issue by astrozot** [sefffal/PairPlots.jl#37]
Thank you for providing this great package!

In many cases, when using the package with many parameters, one will face situations where the default display of confidence limits (credible intervals) is inappropriate. A typical example is when a parameter has small errors in absolute terms, so that the percentiles are all close to each other: then one would see something like , say, $0.06^{+0.00}_{-0.00}$, which does not make too much sense...

A user can customize the display of confidence limits with an appropriate value for `titlefmt` in `MarginConfidenceLimits`, but as far as I understand, the format has to be the same for all parameters. This is often sub-optimal, as some parameters might show credible intervals with too many digits, as in $262.425^{+2.478}_{-3.217}$.

Ideally, one could with relative little effort define a function that uses an appropriate format for each parameter: this would solve most typical situations. In case, I would be happy to help with this.

Additionally, if this is not already possible somehow, it would be anyway useful to have a way to let the use specify a format for each parameter.

**Comment by sefffal** [comment]
Hello @astrozot and thank you for your feature request!

I see two parts that would like to address separately. 

The first is improving customizability of the text that is displayed. Users might want to change the precision, add a text label, or change how the limits are calculated.

I would appreciate your advice on a good API for this. Maybe it could accept a dictionary of format functions?
 
The second is improving the behaviour of the defaults. I would like it so that 0 +- 0 never happens. One way could be to (unless overridden) display these as  (3^+1_-2) X 10^-3 or similar.

**Comment by astrozot** [comment]
Hi @sefffal, thank you for your quick reply!

Yes, my request is really made of two parts.

For the first (improving customizability) a dictionary is surely the easiest way to proceed, and would be most likely very user friendly.

For the second (no more things like 0 +- 0), I think one should split the problem into two parts. The first would be to find out how many significant digits after the dot one needs to show. For that I would use something like 

    digits_after_dot = max(0, 1 - Int(round(log10(error))))

That, for example, would display values as "12.24 +- 0.21", but would instead write "12.2 +- 0.5", which I personally think makes sense (other simple variations would all be OK, of course). That fix should not be too complicated to implement and I believe would solve 90% of the issues.

The second task would be to find out if it is necessary to use a scientific notation. I believe this makes sense only for cases where both the value and the error are exceedingly small, so that one can actually gain space by using the scientific notation. I certainly would not write things like "12.2412 +- 2.1 x 10^-3", as this is not so immediate to understand and would not really save space. However, it might be non-trivial to implement this, so perhaps that part could be left to a user customization?

**Comment by sefffal** [comment]
I'm going to close this issue for now, since I think the default formatter is sufficiently improved. 
Users wanting additional control could create they own object like a MarginConfidenceLimits that has the exact behaviour that they want.
