### ISSUE TITLE
Column vs Row samples

### ISSUE THREAD

**Issue by alecloudenback** [sefffal/PairPlots.jl#40]
The docs say:

    # As always in Julia, columns are treated as variables, and rows as samples.

but is that true? Using Distrubtions.jl, this will produce a 2x10000 matrix:

```julia
rand(MvNormal([0.,0.],[1 0.5; 0.5 1]),10000)
```
Copulas.jl also produces a wide matrix instead of long when sampling. 

I'm not sure what's the preferred approach but I got tripped up here and found myself doing a number of transposes while experimenting with PairPlots.jl

**Comment by sefffal** [comment]
Hi @alecloudenback thanks for the report.
I’m not keen to change this (ultimately we have to pick something!) but I am open to docs fixes.
Do you have any wording suggestions that might have helped you the first time you used the package?

BTW this is more of a fallback. The primary way to use PairPlots is via a Tables.jl compatible table.

**Comment by alecloudenback** [comment]
Maybe just drop the "As always in Julia" part?

**Comment by sefffal** [comment]
Done. Thanks for the feedback!
