### ISSUE TITLE
Truth crashes on NamedTuples in Julia 1.9

### ISSUE THREAD

**Issue by miguelbiron** [sefffal/PairPlots.jl#45]
Edit: we realized that this only affects Julia <=1.9, which is what we're using to build our docs. I've updated the title to reflect this.

------

Hi @sefffal! I'm trying to diagnose a [problem in Pigeons](https://github.com/Julia-Tempering/InferenceReport.jl/pull/25) and -- even though I think this is not the root cause of our failing CI -- I think there's a bug in the `Truth` code, as shown in this CI stacktrace

https://github.com/Julia-Tempering/InferenceReport.jl/actions/runs/8677423183/job/23800806316#step:6:1782

Unless I'm missing something, I think the reason is that for Truth to support `NamedTuple`s -- as the docs say [here](https://github.com/sefffal/PairPlots.jl/blob/228684b30c5195e7863a1a6066b8046468705c2e/src/PairPlots.jl#L31) -- this line

https://github.com/sefffal/PairPlots.jl/blob/228684b30c5195e7863a1a6066b8046468705c2e/src/PairPlots.jl#L40

should really by
```julia
if !(truths isa NamedTuple || keytype(truths) isa Symbol)
```
because `keytype` is not implemented for `NamedTuples`.

Even better, you could have two different constructor methods for `Truth`, where the NamedTuple one would be simpler
```julia
Truth(truths::NamedTuple;label=nothing, kwargs...) = Truth(label, truths, kwargs)

```

**Comment by miguelbiron** [comment]
Oh good catch; just changed the title of the issue to reflect that our docs CI runs on Julia 1.9, which doesn't have this feature.

**Comment by sefffal** [comment]
Thanks both for the report and debugging! I have made your suggested change @miguelbiron. I will merge once CI is green.


BTW, for your videos of the sampling process, have you considered using eg. a Scatter() series? That might also work well.

eg.:

```julia
pairplot(
    chain,
    PairPlots.Series(
        # Replace with sample you want to plot
        (;x=[1], y=[2]),
        label="sample point",
    ) => (
        PairPlots.Scatter(color=:red, markersize=5),
    )
)
```

**Comment by sefffal** [comment]
Merged and tagged.

**Comment by alexandrebouchard** [comment]
> BTW, for your videos of the sampling process, have you considered using eg. a Scatter() series? That might also work well.

Thanks for the suggestion! I think I will give it a try, currently a limitation of the movies feature is that it's a bit slow to generate; worth trying this route to compare running time.

**Comment by miguelbiron** [comment]
Thank you for your quick reply @sefffal ! And I'll look into your suggestion about using Scatter()

**Comment by sefffal** [comment]
I think it will be about the same for the movie. I think it will not improve the generation time at all, unfortunately. 

Once Makie has stabilized their experimental new API (see in this blog https://blog.makie.org/blogposts/v0.20/) we will be able to speed it up a bit.

Until then, you could try turning off some features from PairPlots so that it renders faster. Eg you could turn off all the kde fitting and contours:


```julia
pairplot(
    PairPlots.Series(chain,label="chain", color=:black)=>(
        PairPlots.Scatter(color=:black, markersize=1),
        PairPlots.MarginHist()
    ),
    PairPlots.Series(
        # Replace with sample you want to plot
        (;x=[1], y=[2]),
        label="sample point",
    ) => (
        PairPlots.Scatter(color=:red, markersize=5),
    )
)
```
