### ISSUE TITLE
customize bin_width

### ISSUE THREAD

**Issue by UBCYujia** [sefffal/PairPlots.jl#55]
Hi,

I’m using your project and find it very helpful. Could we add an option to customize the bin width in the pairplot (not just for the contour)? It would be extremely useful.

Thank you!

**Comment by sefffal** [comment]
Hello @UBCYujia , thank you for the feature request! Do you need to specify the bin width separately per series?

**Comment by UBCYujia** [comment]
Thank you for your reply! Yes ,it would be great if we can specify bin width separately!

**Comment by sefffal** [comment]
Hi @UBCYujia , I haven't forgotten this request. I'm still thinking about the best way to provide this option.

We don't currently have any ways in the code to control a visualization element (like a 1D histogram) that is specific to a given column name.

We do currently have a public interface for controlling a histogram calculation: you can provide a function called `prepare_hist` to any of the histogram series. But this function doesn't get called with the row or column names, so it doesn't meet your purposes. 

We might need to release a new major/breaking version of the package to address this.

**Comment by UBCYujia** [comment]
Thank you so much for the update and I understand the challenge.  prepare_hist sounds like a good direction to try first!

**Comment by sefffal** [comment]
Hello @UBCYujia , this is now implemented! Please see the documentation for details. I hope it helps!
