### ISSUE TITLE
Feature request: upper triangular plot

### ISSUE THREAD

**Issue by marcobonici** [sefffal/PairPlots.jl#57]
Hi @sefffal !
After you sent me a snippet of code on how to use PairPlots and obtaina getdist like object, here are my results!

![display](https://github.com/user-attachments/assets/0c3a3f85-7a20-4873-a3d6-21b45428880b)

I am pretty much satisfied! It's basically what I wanted :)
There is only an additional feature I would like to completely transition to PairPlots: plotting in the upper triangular part of the plot!
Notice that this is different to what can be obtained now with `fullgrid`: I want to be able to plot some posteriors *only* in the upper triangular part, like I did here with GetDist

![image](https://github.com/user-attachments/assets/1393d5ac-cabe-4d47-a5d4-383d3f463b46)

Is this something feasible? Thanks in advance!
Marco

**Comment by sefffal** [comment]
Hi @marcobonici , glad to hear you are satisfied!
Yes, I think this could be accomplished. I will take a look.

**Comment by sefffal** [comment]
This is now resolved! See the updated guide section on layouts, once CI has completed.

**Comment by marcobonici** [comment]
Hi @sefffal , thank you!

Here just show the result I obtained with the updated version:)
![display](https://github.com/user-attachments/assets/98b96edf-dad0-44c3-9e5c-b6e04ccd4d3d)

So yeah, I think I will transition to `PairPlots.jl` from now on :)

**Comment by sefffal** [comment]
Great, glad to hear it!
