### ISSUE TITLE
When choosing bandwidth, use the *effective* sample size instead of total sample size

### ISSUE THREAD

**Issue by sefffal** [sefffal/PairPlots.jl#62]
CC @alexandrebouchard

When choosing bandwidth, use the *effective* sample size instead of total sample size

Ideal version: multivariate ESS between each pair of distributions 

Okay version: ESS of both variables individually, take minimum, use in Silverman's rule as usual. Alternatively treat each dimension individually.

**Comment by sefffal** [comment]
I swapped `length(dat)` with `ess(dat)` throughout the code.
Here is an overall comparison before vs after:

<img width="501" alt="image" src="https://github.com/user-attachments/assets/ce08518b-f977-4e10-afef-8aca8f7a5a50"/>


<img width="501" alt="image" src="https://github.com/user-attachments/assets/bde74df3-7eec-4be7-abd4-2868b49b714e"/>


I am very much inclined to make this change.

**Comment by alexandrebouchard** [comment]
Awesome, that looks much better indeed!!
