### ISSUE TITLE
Lens option not working ?

### ISSUE THREAD

**Issue by Simon-Delcamp** [sefffal/PairPlots.jl#7]
First a huge thank you for this package, which is really easy to use and gives great cornerplot !

But I think there is a problem with the "lens" option. I can't reproduce your examples with Julia version 1.7. The errors depend on the type of plot I need. 

If I try to "lens" an histogram (e.g. `corner(table, lens=(:b, :a))` in your example), I have :
`no method matching hist` 

Then, If I try to lens a scatter plot (e.g. `corner(table, lens=:a)` in your example), I have : 
` no method matching (::PairPlots.var"#fmt#31")(::String)
`

I really used your example in a copy-paste way, in a fairly new and simple Julia environment. I will take a look on the code If I have some time :) But I'm not a very advanced Julia user so...

**Comment by sefffal** [comment]
Hi @Simon-Delcamp!
Thanks for reporting this issue.  I can confirm that functionality broke.
I'll take a look over the coming week.
Thanks!

**Comment by Simon-Delcamp** [comment]
No problem! The new branch _lensoption_ is now created.

**Comment by sefffal** [comment]
Thanks @Simon-Delcamp, merged and submitted! 
https://github.com/JuliaRegistries/General/pull/61423
