### ISSUE TITLE
Labels with spaces

### ISSUE THREAD

**Issue by juliohm** [sefffal/PairPlots.jl#8]
![image](https://user-images.githubusercontent.com/3345261/171258581-63eef68a-af0e-4213-9876-edd39e151290.png)

If the column names have spaces, they get erased in the plot. It would be nice to preserve the spaces. In the example above I would like to read `Au ppm` for the concentration of Au in ppm.

**Comment by sefffal** [comment]
Thanks for the remote @juliohm.
Right now the column names are passed through Latexify.jl's `latexify` function which might be eating the spaces.
I'm not sure what the best approach would be, but one possible workaround could be to use latex spacing operators like `\;`.

Alternatively, you can use the `labels` and  `units`  arguments to supply lists of strings directly. The units will be formatted with spacing and go after the numbers in the subplot titles.

**Comment by sefffal** [comment]
Resolved fully by Makie rewrite. You can pass in a Dict mapping table columns to any string, Makie rich text expression, or LaTeX string. The previous behaviour is retained by default.
