### ISSUE TITLE
PairPlots for Makie?

### ISSUE THREAD

**Issue by juliohm** [sefffal/PairPlots.jl#9]
@sefffal any plans to migrate the logic you developed in this package to use Makie as backend instead?

**Comment by sefffal** [comment]
Actually yes, I do a lot of plotting with Makie these days. But probably not in the next few months.

I don’t think Makie recipes s support what we’d need for this so it would have to depend on Makie or MakieCore.

**Comment by juliohm** [comment]
Yes, probably on Makie. I am also maintaining a couple of recipes in Makie these days and needed Makie as a dependency.

**Comment by sefffal** [comment]
Makie support merged to master.
